// follow_boost_org.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

// Build From the Visual Studio IDE
// From Visual Studio's File menu, select New > Project…
//
//In the left - hand pane of the resulting New Project dialog, select Visual C++ > Win32.
//
//In the right - hand pane, select Win32 Console Application(VS8.0) or Win32 Console Project(VS7.1).
//
//In the name field, enter “example”
//
//Right - click example in the Solution Explorer pane and select Properties from the resulting pop - up menu
//
//In Configuration Properties > C / C++ > General > Additional Include Directories, enter the path to the Boost root directory, for example
//
//C : \Program Files\boost\boost_1_75_0
//
//In Configuration Properties > C / C++ > Precompiled Headers, change Use Precompiled Header(/ Yu) to Not Using Precompiled Headers.2
//
//Replace the contents of the example.cpp generated by the IDE with the example code above.
//
//From the Build menu, select Build Solution.
//
//To test your application, hit the F5 keyand type the following into the resulting window, followed by the Return key :

#include <boost/lambda/lambda.hpp>
#include <iostream>
#include <iterator>
#include <algorithm>

int main()
{
    using namespace boost::lambda;
    typedef std::istream_iterator<int> in;

    std::for_each(
        in(std::cin), in(), std::cout << (_1 * 3) << " ");
    //std::cout << "Hello World!\n";
}

// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu

// Tips for Getting Started: 
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file
